[log]
level = 'debug'
backups = 2
maxsize = 1073741824
localtime = true

[global]
max_idle_conns = 100
dial_timeout = 30
dns_ttl = 1800
prefer_ipv6 = false

[upstream]
quic_kr = {scheme='quic', host='kr.phus.lu', port=9443}

[[socks]]
listen = [':10800']
forward_policy = 'bypass_auth'
forward_upstream = 'quic_kr'
