[log]
level = 'debug'
backups = 2
maxsize = 1073741824
localtime = true

[global]
max_idle_conns = 100
dial_timeout = 30
dns_ttl = 1800
prefer_ipv6 = false

[[http]]
listen = [':80']
forward_policy = 'bypass_auth'

[[socks]]
listen = [':1082']
forward_policy = 'bypass_auth'

[[dns]]
listen = [':53']
upstream = ["114.114.114.114"]
