[log]
level = 'debug'
backups = 2
maxsize = 1073741824
localtime = true

[global]
max_idle_conns = 100
dial_timeout = 30
dns_ttl = 1800
prefer_ipv6 = false

[upstream]
example_org = {scheme='https', username='phuslu', password='123456', host='example.org', port=443}

[[http]]
listen = [':80']
pac_enabled = true
proxy_pass = 'file:///C:/Users/phuslu/Desktop'

[[dtls]]
listen = [':443']
psk = 'leader.one'
forward_policy = 'bypass_auth'
